# -*- coding: utf-8 -*-
"""Тексты лендинга AI Strategy: английская и русская версии.

Правило владельца: точек в конце строк нет (ни в заголовках, ни в абзацах).
Структуру собирает tools/build_strategy.py.
"""

EN = {
    "title": "AI Strategy | Where should you start with AI in your business?",
    "meta_desc": "Tell AI Strategy how your business works — it analyzes your processes, finds automation opportunities, defines the roles of people and AI agents, and builds a step-by-step plan to become an AI-First company",
    "video_aria": "Andre explains AI Strategy",
    "role": "AI Strategy",
    "back": "Back",
    "sections": "Sections",
    "close": "Close menu",
    "menu": "Menu",
    "nav": ["The problem", "Businesses", "What you get", "How it works", "Company model", "Learning", "Pricing", "Start"],
    "cta_href": "https://strategy.andre.technology/",
    "cta_top": "Start free",
    "cta_main": "Start for free",
    "cta_how": "See how it works",

    # ── Hero ──
    # две строки, «business» оранжевым — правка владельца
    "h1": 'Where should you start<br>with <span class="hl-p">AI</span> in your <span class="hl-o">business</span>?',
    "hero_lead": "AI Strategy shows you the path from how your business works today to how it should work with AI",
    "hero_body": "Explain how your company operates in your own words",
    "steps_nav": "Steps",

    # ── Questions ──
    "q_head": "The problem is no longer access to AI",
    "questions": [
        "Where should we start?",
        "Which processes should we change first?",
        "What can we delegate to AI?",
        "What should remain with people?",
        "Which AI agents do we actually need?",
        "What should we implement first?",
    ],
    "q_final": "That is exactly what AI Strategy is designed to answer",

    # ── Numbers ──
    "n_eyebrow": "The market today",
    "n_head": "Using AI is not the same as becoming AI-First",
    "numbers": [
        ("76%", "of small businesses already use AI"),
        ("14%", "have fully integrated it into their core operations"),
        ("81%", "of small business owners are open to new AI tools — but one of the biggest barriers is employees not knowing when or how to use them"),
    ],
    "n_foot": "73% say they need more resources and support to implement AI successfully",
    "n_verdict": "Using AI is not the same as becoming AI-First",
    "n_note": "Anthropic’s 2026 SMB work is particularly relevant: more than 1,000 owners attended its workshops, 80% of registrants ran businesses with 5–50 employees, and the leading barrier in its pre-tour survey was uncertainty about when and how to use AI. Nearly two-thirds of exit-survey respondents wanted more hands-on implementation help",

    # ── Promise ──
    "p_head": "You don’t need to be an AI expert to get started",
    "p_sub": "Tell us how your business works. AI Strategy will figure out where AI fits",
    "promise_chips": ["Tools", "Processes", "Agents", "People", "Data", "Priorities"],
    "p_core": "AI-First Strategy",

    # ── Businesses ──
    "b_eyebrow": "Built for your business",
    "b_head": "Your industry, your processes, your metrics",
    "b_sub": "Every business type comes with the AI opportunities and the metrics that matter in it — so the strategy starts from your reality, not from a generic template",
    "biz_ops_label": "AI opportunities",
    "biz_metrics_label": "Effect metrics",
    "biz_explore": "Explore this business",
    "businesses": [
        ("Consulting Business", "Research · analysis · client diagnosis · reporting · presentations · knowledge work",
         ["Project cycle time", "Research hours per engagement", "Consultant utilization"]),
        ("Recruitment Agency", "Sourcing · screening · CV analysis · outreach · interview intelligence · follow-up",
         ["Time-to-fill", "Candidates per recruiter", "Cost per hire"]),
        ("Marketing Agency", "Research · strategy · campaigns · reporting · optimization · client communication",
         ["Campaign launch time", "Reporting hours", "CAC / ROAS"]),
        ("Content Agency", "Research · ideation · scripts · copy · repurposing · localization · publishing",
         ["Time-to-publish", "Output per employee", "Cost per asset"]),
        ("Call Center", "Inbound calls · qualification · routing · standard requests · summaries · QA",
         ["Average handling time", "Containment rate", "Cost per contact"]),
        ("Customer Support", "Classification · knowledge retrieval · responses · troubleshooting · escalation · QA",
         ["First response time", "Resolution time", "Ticket deflection", "CSAT"]),
        ("Design Agency", "Brief analysis · research · concepts · variations · production · review",
         ["Design cycle time", "Revision rounds", "Concepts per brief"]),
        ("Software Development", "Requirements · architecture · coding · review · testing · documentation · release",
         ["Lead time for changes", "Cycle time", "Deployment frequency", "Defect rate"]),
    ],
    "b_all": "Explore all 50 business types",
    "b_arch": "50 categories → <b>~500 specializations</b>, 10 inside every business",
    "b_metrics_note": "The metrics are presented as metrics AI Strategy can help you target and track, not as guaranteed improvement percentages",

    # ── Deliverables ──
    "d_eyebrow": "What you get",
    "d_head": "Eight artifacts that stack into one model of your company",
    "d_sub": "Not a report to read once — a working model of your business you can keep using",
    "deliverables": [
        ("AI Maturity Assessment", "Where your company stands across seven dimensions, and which one holds you back"),
        ("Process Map", "Your business broken down into processes, in your own words"),
        ("AS-IS", "How the work really flows today — people, systems, documents"),
        ("AI Opportunities", "Operations AI can take over, with potential impact and complexity"),
        ("Human + AI", "Who does what: operator, supervisor, manager or co-creator"),
        ("TO-BE", "The same business redesigned around AI"),
        ("AI Agent Specifications", "A build-ready passport for every agent your business needs"),
        ("Roadmap", "What to implement first, second and third"),
    ],
    "d_hint": "Scroll the cards",

    # ── Ten steps ──
    "s_eyebrow": "How it works",
    "s_head": "Ten steps from “we should use AI” to “here is what we build”",
    "s_sub": "You talk about your business the way you understand it. The system does the methodology part — and shows you the result at every step",
    "steps": [
        ("AI Maturity", "Understand where you are today",
         "35 questions across seven dimensions turn into an AI Maturity Index — a business diagnostic, not a quiz. You see which dimension is holding the company back before anything is redesigned", ""),
        ("Voice input", "Just talk",
         "Tell the system how your company works, out loud and in your own words. The transcript does not stay text — the words become structured process cards in front of you", ""),
        ("Process Discovery", "Your business, laid out as processes",
         "The system proposes the processes it heard: lead generation, sales, onboarding, delivery, support, billing. Rename, delete, add, reorder",
         "You always have the final say"),
        ("Process Intelligence", "One process opens into real operations",
         "Pick a process and it expands step by step. Click any operation and you see its input, output, role, system, method and metric — the level where automation decisions are actually made", ""),
        ("Cognitive Intelligence", "Processes tell us what people do. Cognitive Intelligence tells us how they decide",
         "For every human decision the system captures what information you look at, which criteria matter, what you know from experience, what happens when information is missing and when you escalate",
         "Those answers become Decision Logic — and later the reasoning inside your AI agent"),
        ("AS-IS", "See how your business works today",
         "The whole process zooms out into one map: people, systems and documents each read differently, and bottlenecks surface on their own. Analytical, not alarming", ""),
        ("AI Opportunities", "See what AI can take over",
         "Operations that AI can handle start to glow, each with potential impact and complexity. You decide what to automate — the system only shows where it is possible", ""),
        ("Human + AI", "Decide the role of the human before redesigning the process",
         "For every automated operation you choose how people stay involved: operator, supervisor, manager or co-creator. AI produces the draft, a person approves it — or the other way around", ""),
        ("TO-BE", "See how the same business should work with AI",
         "The AS-IS map transforms: some operations disappear, some merge, AI agents appear, and people move from execution toward approval and supervision", ""),
        ("AI Agent Passport", "Leave knowing exactly what AI to build",
         "Every AI node opens into a specification: functions, inputs, outputs, systems, skills, decision rules, metrics, the human role and the instructions",
         "Don’t leave with “we need AI” — leave with what to build first"),
    ],

    "stage": {
        "dims": ["Strategy", "Data", "Technology", "Processes", "People", "Governance", "Culture"],
        "s1_bar": "AI Maturity Assessment",
        "s1_index": "AI Maturity Index",
        "s1_weak": "Weakest dimension: People — skills and roles for working with AI",
        "s2_bar": "Tell us how your business works",
        "s2_quote": "“We receive most of our leads through the website, then a manager qualifies them and books a call…”",
        "s2_cards": ["Lead Generation", "Sales", "Onboarding"],
        "s3_bar": "Process Discovery",
        "s3_cards": ["Lead Generation", "Sales", "Client Onboarding", "Delivery", "Support", "Billing"],
        "s3_rename": "Rename", "s3_add": "Add", "s3_delete": "Delete", "s3_drag": "Reorder",
        "s4_bar": "Sales · operations",
        "s4_ops": ["Lead arrives", "Qualification", "Meeting", "Proposal", "Negotiation", "Close", "Handoff"],
        "s4_panel": "Operation · Qualification",
        "s4_fields": [("Input", "Inbound lead + form"), ("Output", "Qualified or rejected"), ("Role", "Sales manager"),
                      ("System", "CRM"), ("Method", "Call + checklist"), ("Metric", "Qualification rate")],
        "s5_bar": "Cognitive Intelligence",
        "s5_node": "Human decision · Qualify the lead",
        "s5_qs": ["What information do you look at?", "Which criteria matter?", "What do you know from experience?",
                  "What happens when information is missing?", "When do you escalate?"],
        "s5_logic": "Decision Logic",
        "s6_bar": "AS-IS · how it works today",
        "l_human": "People", "l_system": "Systems", "l_doc": "Documents", "l_bottleneck": "Bottleneck",
        "s6_nodes": [("human", "fa-user", "Lead arrives"), ("sys", "fa-database", "CRM"),
                     ("human", "fa-user", "Qualification"), ("doc", "fa-file-lines", "Checklist"),
                     ("human", "fa-user", "Meeting"), ("doc", "fa-file-lines", "Proposal"),
                     ("human", "fa-user", "Follow-up"), ("sys", "fa-chart-line", "Reporting")],
        "s7_bar": "AI Opportunities",
        "s7_nodes": [("human", "fa-user", "Lead arrives"), ("sys glow", "fa-database", "CRM update"),
                     ("human glow", "fa-user", "Qualification"), ("doc glow", "fa-file-lines", "Document analysis"),
                     ("human", "fa-user", "Meeting"), ("doc", "fa-file-lines", "Proposal"),
                     ("human glow", "fa-user", "Follow-up"), ("sys glow", "fa-chart-line", "Reporting")],
        "s7_impact": "Potential impact · high", "s7_complexity": "Complexity · medium", "s7_automate": "Automate",
        "s8_bar": "Human + AI",
        "s8_op": "Qualification · automated",
        "s8_roles": ["Operator", "Supervisor", "Manager", "Co-creator"],
        "s8_flow": ["AI qualifies the lead", "Draft summary + score", "Supervisor approves"],
        "s9_asis": "AS-IS", "s9_tobe": "TO-BE",
        "s9_caption": "Operations merge, AI agents appear, people move toward approval and supervision",
        "s9_nodes": [("human", "", "fa-user", "Lead arrives"), ("ai add", "", "fa-robot", "AI Qualification"),
                     ("human drop", "", "fa-user", "Manual qualification"), ("ai add", "", "fa-robot", "AI Document analysis"),
                     ("human", "", "fa-user-check", "Meeting"), ("ai add", "", "fa-robot", "AI Proposal draft"),
                     ("human drop", "", "fa-user", "Manual follow-up"), ("ai add", "", "fa-chart-line", "AI Reporting")],
        "s10_bar": "AI Agent Passport",
        "s10_name": "AI Sales Qualification Agent",
        "s10_fields": [("Functions", "Qualifies inbound leads, scores them, books the call"),
                       ("Inputs", "Form, website behavior, CRM history"),
                       ("Outputs", "Score, summary, next step"),
                       ("Systems", "CRM, calendar, email"),
                       ("Skills", "Extraction, scoring, writing"),
                       ("Decision rules", "Captured from your manager’s own logic"),
                       ("Metrics", "Qualification rate, response time"),
                       ("Human role", "Supervisor — approves edge cases"),
                       ("Instructions", "Ready to hand to a builder or to Neuronium")],
    },

    # ── Company model ──
    "m_eyebrow": "Company model",
    "m_head": "From one process to an AI-First Operating Model",
    "m_sub": "Processes stop being separate diagrams: departments, people, roles, systems, artifacts and AI agents assemble into one map of the company",
    "model_nodes": [("human", "fa-building", "Departments"), ("human", "fa-users", "People"), ("human", "fa-id-badge", "Roles"),
                    ("sys", "fa-diagram-project", "Processes"), ("sys", "fa-database", "Systems"),
                    ("doc", "fa-file-lines", "Artifacts"), ("ai", "fa-robot", "AI Agents"), ("ai", "fa-sitemap", "AI-First Model")],

    # ── Team ──
    "t_eyebrow": "Team",
    "t_head": "Start with yourself. Then bring in your team",
    "t_l_head": "Founder",
    "t_l_body": "The owner describes the company from the top down: what the business does, how money comes in, what matters",
    "t_r_head": "Employees",
    "t_r_body": "Employees add the processes they understand best — the details no one at the top ever sees",
    "t_foot": "AI Strategy brings everything together into one operating model",

    # ── Learning ──
    "l_eyebrow": "Learning",
    "l_head": "Learn while you transform",
    "l_sub": "Free education is built directly into AI Strategy. You and your team can learn the new roles and skills required to work in an AI-First company — including how to design, build and manage AI agents yourselves",
    "learn_steps": [
        ("Roadmap", "Build AI Support Agent", "An item from your own strategy, not an abstract course"),
        ("Education", "Learn how to build AI agents", "The lesson opens exactly where the roadmap needs it"),
        ("Skill", "Completed", "The skill lands in your team, not in a certificate"),
        ("Build", "Agent in production", "And the roadmap moves one step forward"),
    ],
    "l_foot": "The goal is not only to tell you which agents your business needs. It is to help you or your team build and manage them independently. If additional support is needed, you can work directly with <strong>Andre AI Technologies</strong> on implementation, consulting and more complex transformation projects",

    # ── Cost ──
    "c_eyebrow": "Cost of clarity",
    "c_head": "You don’t need a six-figure consulting engagement to understand where to start",
    "cost_cols": [
        ("Traditional consulting", "$500K+", "Months of interviews, workshops, analysis and presentations"),
        ("AI transformation consulting", "$2K–$50K", "Typical SMB AI readiness and strategy projects commonly fall in the low-thousands to tens-of-thousands range, depending on scope"),
        ("AI Strategy", "From $59", "Start with one process for free. Build the strategy yourself. Bring in human experts only when you actually need them"),
    ],
    "c_note": "Ontora itself currently compares a McKinsey-style engagement at $500K+ with approximately $50K for its AI-powered approach. Published 2026 SMB AI-consulting guides commonly place assessments and strategy engagements around $2K–$25K, depending on depth and scope",

    # ── Pricing ──
    "pr_eyebrow": "Pricing",
    "pr_head": "Start small. Transform as much of the company as you need",
    "plans": [
        ("", "Free", "$0", "1 process", "See the complete methodology on a real process from your business", "Start free"),
        ("", "Startup", "$59", "60 operations", "For founders and small teams", "Choose Startup"),
        ("", "SMB", "$199", "300 operations", "For growing businesses with multiple functions and processes", "Choose SMB"),
        ("best", "Company", "$499", "1,000 operations", "For company-wide transformation", "Choose Company"),
    ],
    "best_value": "Best value",
    "best_hint": "Best value for complete transformation",
    "pr_once": "One-time purchase. No subscription required",
    "pr_once_sub": "Pay once for the amount of your business you want to analyze and redesign",
    "pr_what": "What is an operation?",
    "op_chain": ["Lead received", "Qualify", "Schedule meeting", "Meeting", "Proposal", "Negotiate", "Close"],
    "pr_ops_note": "Seven operations — that is one small sales process",

    # ── Final ──
    "f_1": "Where should you start with AI?",
    "f_2": "You don’t need to know",
    "f_3": "That is what AI Strategy is for",
    "final_flow": ["Your business today", "Understand", "Redesign", "AI Agents", "AI-First"],
    "final_list": [
        "where you are today",
        "what is worth changing",
        "what to delegate to AI",
        "what should remain with people",
        "which AI agents to create",
        "and in what order to implement everything",
    ],
    "f_cta": "Analyze your first process for free",
}

RU = {
    "title": "AI Strategy | С чего начать внедрять ИИ в вашем бизнесе?",
    "meta_desc": "Расскажите AI Strategy, как устроен ваш бизнес — система разберёт процессы, найдёт возможности для автоматизации, определит роли людей и ИИ-агентов и соберёт пошаговый план перехода к AI-First компании",
    "video_aria": "Андре рассказывает про AI Strategy",
    "role": "ИИ-стратегия",
    "back": "Назад",
    "sections": "Разделы",
    "close": "Закрыть меню",
    "menu": "Меню",
    "nav": ["Проблема", "Бизнесы", "Что вы получите", "Как это работает", "Модель компании", "Обучение", "Тарифы", "Начать"],
    "cta_href": "https://strategy.andre.technology/",
    "cta_top": "Начать бесплатно",
    "cta_main": "Начать бесплатно",
    "cta_how": "Как это работает",

    "h1": 'С чего начать внедрять <span class="hl-p">ИИ</span><br>в вашем <span class="hl-o">бизнесе</span>?',
    "hero_lead": "AI Strategy показывает путь от того, как ваш бизнес работает сегодня, к тому, как он должен работать с ИИ",
    "hero_body": "Расскажите своими словами, как работает ваша компания",
    "steps_nav": "Шаги",

    "q_head": "Проблема больше не в доступе к ИИ",
    "questions": [
        "С чего начать?",
        "Какие процессы менять первыми?",
        "Что можно отдать ИИ?",
        "Что должно остаться за людьми?",
        "Какие ИИ-агенты нам действительно нужны?",
        "Что внедрять в первую очередь?",
    ],
    "q_final": "Именно на эти вопросы и отвечает AI Strategy",

    "n_eyebrow": "Рынок сегодня",
    "n_head": "Пользоваться ИИ и быть AI-First — не одно и то же",
    "numbers": [
        ("76%", "малых компаний уже используют ИИ"),
        ("14%", "полностью встроили его в основную работу"),
        ("81%", "владельцев малого бизнеса открыты к новым ИИ-инструментам — но один из главных барьеров в том, что сотрудники не знают, когда и как их применять"),
    ],
    "n_foot": "73% говорят, что им нужно больше ресурсов и поддержки, чтобы довести внедрение ИИ до результата",
    "n_verdict": "Пользоваться ИИ и быть AI-First — не одно и то же",
    "n_note": "Показательна работа Anthropic с малым бизнесом в 2026 году: воркшопы посетили более 1000 владельцев, 80% зарегистрировавшихся вели компании на 5–50 человек, а главным барьером в предварительном опросе была неопределённость — когда и как применять ИИ. Почти две трети участников итогового опроса просили больше практической помощи с внедрением",

    "p_head": "Чтобы начать, не нужно быть экспертом по ИИ",
    "p_sub": "Расскажите, как работает ваш бизнес. AI Strategy сам разберётся, где место ИИ",
    "promise_chips": ["Инструменты", "Процессы", "Агенты", "Люди", "Данные", "Приоритеты"],
    "p_core": "AI-First стратегия",

    "b_eyebrow": "Под ваш бизнес",
    "b_head": "Ваша отрасль, ваши процессы, ваши метрики",
    "b_sub": "У каждого типа бизнеса свои возможности для ИИ и свои метрики — стратегия начинается с вашей реальности, а не с универсального шаблона",
    "biz_ops_label": "Возможности ИИ",
    "biz_metrics_label": "Метрики эффекта",
    "biz_explore": "Открыть этот бизнес",
    "businesses": [
        ("Консалтинг", "Исследования · анализ · диагностика клиента · отчёты · презентации · работа со знаниями",
         ["Срок проекта", "Часы исследований", "Загрузка консультантов"]),
        ("Кадровое агентство", "Поиск · скрининг · разбор резюме · аутрич · аналитика интервью · follow-up",
         ["Срок закрытия вакансии", "Кандидатов на рекрутера", "Стоимость найма"]),
        ("Маркетинговое агентство", "Исследования · стратегия · кампании · отчётность · оптимизация · общение с клиентом",
         ["Срок запуска кампании", "Часы на отчётность", "CAC / ROAS"]),
        ("Контент-агентство", "Исследования · идеи · сценарии · тексты · переупаковка · локализация · публикация",
         ["Срок до публикации", "Выпуск на сотрудника", "Стоимость единицы контента"]),
        ("Колл-центр", "Входящие звонки · квалификация · маршрутизация · типовые запросы · саммари · контроль качества",
         ["Среднее время обработки", "Доля автоответов", "Стоимость контакта"]),
        ("Поддержка клиентов", "Классификация · поиск по базе знаний · ответы · диагностика · эскалация · контроль качества",
         ["Время первого ответа", "Время решения", "Доля закрытых без человека", "CSAT"]),
        ("Дизайн-агентство", "Разбор брифа · исследование · концепции · вариации · продакшн · ревью",
         ["Срок дизайн-цикла", "Круги правок", "Концепций на бриф"]),
        ("Разработка ПО", "Требования · архитектура · код · ревью · тестирование · документация · релиз",
         ["Время до изменения", "Срок цикла разработки", "Частота релизов", "Доля дефектов"]),
    ],
    "b_all": "Посмотреть все 50 типов бизнеса",
    "b_arch": "50 категорий → <b>~500 специализаций</b>, по 10 внутри каждого бизнеса",
    "b_metrics_note": "Метрики показаны как то, на что AI Strategy помогает целиться и что отслеживать, а не как гарантированные проценты улучшения",

    "d_eyebrow": "Что вы получите",
    "d_head": "Восемь артефактов, которые складываются в модель вашей компании",
    "d_sub": "Не отчёт, который читают один раз, а рабочая модель бизнеса, которой можно пользоваться дальше",
    "deliverables": [
        ("Диагностика ИИ-зрелости", "Где компания находится по семи измерениям и что именно её тормозит"),
        ("Карта процессов", "Ваш бизнес, разложенный на процессы вашими же словами"),
        ("AS-IS", "Как работа идёт сегодня — люди, системы, документы"),
        ("Возможности ИИ", "Операции, которые ИИ может взять на себя, с эффектом и сложностью"),
        ("Человек + ИИ", "Кто что делает: оператор, супервайзер, управляющий или соавтор"),
        ("TO-BE", "Тот же бизнес, перестроенный вокруг ИИ"),
        ("Спецификации ИИ-агентов", "Готовый к сборке паспорт каждого нужного агента"),
        ("Дорожная карта", "Что внедрять первым, вторым и третьим"),
    ],
    "d_hint": "Листайте карточки",

    "s_eyebrow": "Как это работает",
    "s_head": "Десять шагов от «нам нужен ИИ» до «вот что мы строим»",
    "s_sub": "Вы рассказываете о бизнесе так, как понимаете его сами. Методологию берёт на себя система — и показывает результат на каждом шаге",
    "steps": [
        ("ИИ-зрелость", "Понять, где вы сейчас",
         "35 вопросов по семи измерениям превращаются в индекс ИИ-зрелости — это бизнес-диагностика, а не тест. Видно, какое измерение тормозит компанию, ещё до того, как что-то перестраивать", ""),
        ("Голосовой ввод", "Просто расскажите",
         "Расскажите вслух и своими словами, как устроена компания. Расшифровка не остаётся текстом — слова превращаются в структурированные карточки процессов прямо у вас на глазах", ""),
        ("Поиск процессов", "Ваш бизнес, разложенный на процессы",
         "Система предлагает процессы, которые услышала: привлечение лидов, продажи, онбординг, поставка, поддержка, счета. Переименуйте, удалите, добавьте, поменяйте местами",
         "Последнее слово всегда за вами"),
        ("Разбор процесса", "Один процесс раскрывается в реальные операции",
         "Выберите процесс — и он развернётся по шагам. Нажмите на операцию: вход, выход, роль, система, метод и метрика. Это тот уровень, на котором и принимаются решения об автоматизации", ""),
        ("Когнитивная разведка", "Процессы говорят, что делают люди. Когнитивная разведка — как они решают",
         "Для каждого человеческого решения система фиксирует, на что вы смотрите, какие критерии важны, что вы знаете из опыта, что происходит при нехватке информации и когда вы эскалируете",
         "Эти ответы становятся логикой решений — а позже рассуждением внутри вашего ИИ-агента"),
        ("AS-IS", "Увидеть, как бизнес работает сегодня",
         "Процесс отдаляется в одну карту: люди, системы и документы читаются по-разному, а узкие места проявляются сами. Аналитично, без красной краски по всему экрану", ""),
        ("Возможности ИИ", "Увидеть, что ИИ может взять на себя",
         "Операции, посильные ИИ, начинают светиться — у каждой свой потенциальный эффект и сложность. Что автоматизировать, решаете вы: система лишь показывает, где это возможно", ""),
        ("Человек + ИИ", "Решите роль человека до того, как перестраивать процесс",
         "Для каждой автоматизированной операции вы выбираете, как в ней остаётся человек: оператор, супервайзер, управляющий или соавтор. ИИ готовит черновик, человек утверждает — или наоборот", ""),
        ("TO-BE", "Увидеть, как тот же бизнес должен работать с ИИ",
         "Карта AS-IS перестраивается: часть операций исчезает, часть сливается, появляются ИИ-агенты, а люди уходят от исполнения к утверждению и надзору", ""),
        ("Паспорт ИИ-агента", "Уйти, точно зная, какой ИИ строить",
         "Каждый ИИ-узел раскрывается в спецификацию: функции, входы, выходы, системы, навыки, правила решений, метрики, роль человека и инструкции",
         "Не «нам нужен ИИ», а понятный первый агент к сборке"),
    ],

    "stage": {
        "dims": ["Стратегия", "Данные", "Технологии", "Процессы", "Люди", "Управление", "Культура"],
        "s1_bar": "Диагностика ИИ-зрелости",
        "s1_index": "Индекс ИИ-зрелости",
        "s1_weak": "Самое слабое измерение: люди — навыки и роли для работы с ИИ",
        "s2_bar": "Расскажите, как работает бизнес",
        "s2_quote": "«Большинство заявок приходит с сайта, дальше менеджер квалифицирует их и назначает созвон…»",
        "s2_cards": ["Привлечение лидов", "Продажи", "Онбординг"],
        "s3_bar": "Поиск процессов",
        "s3_cards": ["Привлечение лидов", "Продажи", "Онбординг клиента", "Поставка", "Поддержка", "Счета"],
        "s3_rename": "Переименовать", "s3_add": "Добавить", "s3_delete": "Удалить", "s3_drag": "Поменять местами",
        "s4_bar": "Продажи · операции",
        "s4_ops": ["Пришёл лид", "Квалификация", "Встреча", "Предложение", "Переговоры", "Сделка", "Передача"],
        "s4_panel": "Операция · квалификация",
        "s4_fields": [("Вход", "Заявка + форма"), ("Выход", "Квалифицирован или отказ"), ("Роль", "Менеджер по продажам"),
                      ("Система", "CRM"), ("Метод", "Звонок по чек-листу"), ("Метрика", "Доля квалификаций")],
        "s5_bar": "Когнитивная разведка",
        "s5_node": "Решение человека · квалифицировать лид",
        "s5_qs": ["На какую информацию вы смотрите?", "Какие критерии важны?", "Что вы знаете из опыта?",
                  "Что делать, если данных не хватает?", "Когда вы эскалируете?"],
        "s5_logic": "Логика решения",
        "s6_bar": "AS-IS · как работает сегодня",
        "l_human": "Люди", "l_system": "Системы", "l_doc": "Документы", "l_bottleneck": "Узкое место",
        "s6_nodes": [("human", "fa-user", "Пришёл лид"), ("sys", "fa-database", "CRM"),
                     ("human", "fa-user", "Квалификация"), ("doc", "fa-file-lines", "Чек-лист"),
                     ("human", "fa-user", "Встреча"), ("doc", "fa-file-lines", "Предложение"),
                     ("human", "fa-user", "Follow-up"), ("sys", "fa-chart-line", "Отчётность")],
        "s7_bar": "Возможности ИИ",
        "s7_nodes": [("human", "fa-user", "Пришёл лид"), ("sys glow", "fa-database", "Обновление CRM"),
                     ("human glow", "fa-user", "Квалификация"), ("doc glow", "fa-file-lines", "Разбор документов"),
                     ("human", "fa-user", "Встреча"), ("doc", "fa-file-lines", "Предложение"),
                     ("human glow", "fa-user", "Follow-up"), ("sys glow", "fa-chart-line", "Отчётность")],
        "s7_impact": "Эффект · высокий", "s7_complexity": "Сложность · средняя", "s7_automate": "Автоматизировать",
        "s8_bar": "Человек + ИИ",
        "s8_op": "Квалификация · автоматизирована",
        "s8_roles": ["Оператор", "Супервайзер", "Управляющий", "Соавтор"],
        "s8_flow": ["ИИ квалифицирует лид", "Черновик саммари и оценка", "Супервайзер утверждает"],
        "s9_asis": "AS-IS", "s9_tobe": "TO-BE",
        "s9_caption": "Операции сливаются, появляются ИИ-агенты, люди уходят к утверждению и надзору",
        "s9_nodes": [("human", "", "fa-user", "Пришёл лид"), ("ai add", "", "fa-robot", "ИИ-квалификация"),
                     ("human drop", "", "fa-user", "Ручная квалификация"), ("ai add", "", "fa-robot", "ИИ-разбор документов"),
                     ("human", "", "fa-user-check", "Встреча"), ("ai add", "", "fa-robot", "ИИ-черновик предложения"),
                     ("human drop", "", "fa-user", "Ручной follow-up"), ("ai add", "", "fa-chart-line", "ИИ-отчётность")],
        "s10_bar": "Паспорт ИИ-агента",
        "s10_name": "ИИ-агент квалификации продаж",
        "s10_fields": [("Функции", "Квалифицирует входящие лиды, оценивает их, назначает созвон"),
                       ("Входы", "Форма, поведение на сайте, история в CRM"),
                       ("Выходы", "Оценка, саммари, следующий шаг"),
                       ("Системы", "CRM, календарь, почта"),
                       ("Навыки", "Извлечение данных, скоринг, текст"),
                       ("Правила решений", "Сняты с логики вашего же менеджера"),
                       ("Метрики", "Доля квалификаций, время ответа"),
                       ("Роль человека", "Супервайзер — утверждает спорные случаи"),
                       ("Инструкции", "Готовы к передаче разработчику или в Нейроний")],
    },

    "m_eyebrow": "Модель компании",
    "m_head": "От одного процесса к AI-First операционной модели",
    "m_sub": "Процессы перестают быть отдельными схемами: подразделения, люди, роли, системы, артефакты и ИИ-агенты собираются в одну карту компании",
    "model_nodes": [("human", "fa-building", "Подразделения"), ("human", "fa-users", "Люди"), ("human", "fa-id-badge", "Роли"),
                    ("sys", "fa-diagram-project", "Процессы"), ("sys", "fa-database", "Системы"),
                    ("doc", "fa-file-lines", "Артефакты"), ("ai", "fa-robot", "ИИ-агенты"), ("ai", "fa-sitemap", "AI-First модель")],

    "t_eyebrow": "Команда",
    "t_head": "Начните с себя. Потом подключите команду",
    "t_l_head": "Основатель",
    "t_l_body": "Владелец описывает компанию сверху вниз: чем занимается бизнес, откуда приходят деньги, что важно",
    "t_r_head": "Сотрудники",
    "t_r_body": "Сотрудники добавляют процессы, которые знают лучше всех — детали, которых сверху не видно",
    "t_foot": "AI Strategy сводит всё это в одну операционную модель",

    "l_eyebrow": "Обучение",
    "l_head": "Учитесь по ходу трансформации",
    "l_sub": "Бесплатное обучение встроено прямо в AI Strategy. Вы и ваша команда осваиваете новые роли и навыки работы в AI-First компании — в том числе то, как самим проектировать, собирать и вести ИИ-агентов",
    "learn_steps": [
        ("Дорожная карта", "Собрать ИИ-агента поддержки", "Пункт из вашей же стратегии, а не абстрактный курс"),
        ("Обучение", "Как собирать ИИ-агентов", "Урок открывается ровно там, где он нужен по карте"),
        ("Навык", "Освоен", "Навык остаётся в команде, а не в сертификате"),
        ("Сборка", "Агент в работе", "И дорожная карта двигается на шаг вперёд"),
    ],
    "l_foot": "Цель не только в том, чтобы сказать, какие агенты нужны бизнесу. Цель — чтобы вы или ваша команда могли собрать их и вести самостоятельно. Если нужна дополнительная поддержка, можно работать напрямую с <strong>Andre AI Technologies</strong> по внедрению, консалтингу и более сложным проектам трансформации",

    "c_eyebrow": "Цена ясности",
    "c_head": "Чтобы понять, с чего начать, не нужен консалтинговый проект за сотни тысяч долларов",
    "cost_cols": [
        ("Классический консалтинг", "$500K+", "Месяцы интервью, воркшопов, анализа и презентаций"),
        ("Консалтинг по ИИ-трансформации", "$2K–$50K", "Типовые проекты по оценке готовности и ИИ-стратегии для малого и среднего бизнеса обычно укладываются в диапазон от нескольких тысяч до десятков тысяч долларов — в зависимости от объёма"),
        ("AI Strategy", "От $59", "Начните с одного процесса бесплатно. Соберите стратегию сами. Привлекайте людей-экспертов тогда, когда они действительно нужны"),
    ],
    "c_note": "Сама Ontora сейчас сравнивает проект уровня McKinsey за $500K+ примерно с $50K за свой подход на ИИ. Опубликованные в 2026 году гайды по ИИ-консалтингу для малого и среднего бизнеса обычно оценивают диагностику и стратегию в $2K–$25K — в зависимости от глубины и объёма",

    "pr_eyebrow": "Тарифы",
    "pr_head": "Начните с малого. Перестраивайте столько компании, сколько нужно",
    "plans": [
        ("", "Бесплатно", "$0", "1 процесс", "Пройдите всю методологию на реальном процессе вашего бизнеса", "Начать бесплатно"),
        ("", "Стартап", "$59", "60 операций", "Для основателей и небольших команд", "Выбрать «Стартап»"),
        ("", "SMB", "$199", "300 операций", "Для растущего бизнеса с несколькими функциями и процессами", "Выбрать SMB"),
        ("best", "Компания", "$499", "1 000 операций", "Для трансформации всей компании", "Выбрать «Компанию»"),
    ],
    "best_value": "Лучшее предложение",
    "best_hint": "Лучший выбор для полной трансформации",
    "pr_once": "Разовая покупка. Без подписки",
    "pr_once_sub": "Платите один раз за тот объём бизнеса, который хотите разобрать и перестроить",
    "pr_what": "Что такое операция?",
    "op_chain": ["Пришёл лид", "Квалификация", "Назначить встречу", "Встреча", "Предложение", "Переговоры", "Сделка"],
    "pr_ops_note": "Семь операций — это один небольшой процесс продаж",

    "f_1": "С чего начать внедрять ИИ?",
    "f_2": "Вам не обязательно это знать",
    "f_3": "Для этого и нужен AI Strategy",
    "final_flow": ["Ваш бизнес сегодня", "Понять", "Перестроить", "ИИ-агенты", "AI-First"],
    "final_list": [
        "где вы находитесь сегодня",
        "что стоит менять",
        "что отдать ИИ",
        "что должно остаться за людьми",
        "каких ИИ-агентов создать",
        "и в каком порядке всё это внедрять",
    ],
    "f_cta": "Разобрать первый процесс бесплатно",
}
